//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour_du_lich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctdoan
    {
        public string madoan { get; set; }
        public string makh { get; set; }
        public string mota { get; set; }
    
        public virtual doan doan { get; set; }
        public virtual khachhang khachhang { get; set; }
    }
}
