//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour_du_lich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gia
    {
        public string magia { get; set; }
        public string matour { get; set; }
        public Nullable<double> giatien { get; set; }
        public Nullable<System.DateTime> tgbd { get; set; }
        public Nullable<System.DateTime> tgkt { get; set; }
    
        public virtual tour tour { get; set; }
    }
}
