//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour_du_lich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phancong
    {
        public string madoan { get; set; }
        public string manv { get; set; }
        public string nhiemvu { get; set; }
    
        public virtual doan doan { get; set; }
        public virtual nhanvien nhanvien { get; set; }
    }
}
